### ISSUE TITLE
Aerospike Design

### ISSUE THREAD

**Issue by animushax** [mvernacc/aerospike-nozzle-design-gui#1]
Hi there,

My colleague and I are working on a project using an aerospike. You'll be happy to know your code is the only one we've found to work, in its existing condition on the Internet. We are having some issues getting a sensible geometry, can you advise on what we may be doing incorrectly? See attached images for our values.

![screen shot 2018-01-08 at 7 04 47 pm](https://user-images.githubusercontent.com/35242710/34698668-53114e36-f4a7-11e7-80c2-736b35adc6c9.png)

<img width="813" alt="screen shot 2018-01-08 at 7 05 11 pm" src="https://user-images.githubusercontent.com/35242710/34698674-59060390-f4a7-11e7-82ef-30c8bbafbb11.png">

**Comment by mvernacc** [comment]
The geometry you show in "Figure 1" does look reasonable.

I assume the attached "Figure 1" is a plot of the coordinates in the "*_shroud_curve.txt" (red) and *"_spike_curve.txt" (blue) output files. The coordinates in these files give the geometry of the spike and shroud contours, in units of millimeters. The coordinates are listed in (0, axial, radial) order.

In your figure, the vertical axis is the radial direction and the horizontal axis is the axial direction. The supersonic portion of the spike would be formed by revolving the blue curve around the horizontal axis.

**Comment by animushax** [comment]
Yes those are the plots, and I understand the revolution of the plots, I'm
glad you think they are sufficient.

Can we set up a quick phone call? I would be immensely grateful and it may
clear up some other manufacturing questions.

I think I sent you an email via your school email, I can send contact info
there if that works. I'm not sure how discreet this reply will be.

Cheers,

Dan
