### ISSUE TITLE
Determining exit radius

### ISSUE THREAD

**Issue by murralog** [mvernacc/aerospike-nozzle-design-gui#2]
Hi, ...
I am doing a research project on the thrust performance of truncated linear aerospikes vs normal linear aerospikes at different vacuums. I came across your software and your code was a very helpful tool for determining the geometry of the spike. I am confused with the Exit Radius/ Thrust variable that your code requires to run. In my studies, I have run across this variable before but I do not know how to determine it. I am using a D11-P Estes rocket engine and my other variables are listed in the picture below

Could you tell me how to determine this variable or link me to a resource so I can solve it myself? Thank you!
![image](https://user-images.githubusercontent.com/43050195/72669201-a61ddd80-39f4-11ea-992e-c2aeef5c8484.png)

**Comment by zhukgleb** [comment]
Hello! Sorry for the late reply. I'm not a author this code, but your
problem solve this
<https://github.com/Doomed09/aerospike-nozzle-design-gui/blob/master/Spike%20Contour%20Algorithm.pdf>.

**Comment by murralog** [comment]
Sorry for the late reply. 
I ran across this document in my research but it didn't seem to answer my question. In the doc, It shows how to creates the ratio of throat gap to Re using the area of the spike and angle of the cowl. From my understanding, it seems that Re cannot be found unless modeling a preexisting spike. Could you possibly walk me through this or give me an example. 
Thank you
![image](https://user-images.githubusercontent.com/43050195/72735923-6248e680-3b62-11ea-8fcf-8c6551633b61.png)
![image](https://user-images.githubusercontent.com/43050195/72735940-683ec780-3b62-11ea-95e8-8019e69210cb.png)

**Comment by mvernacc** [comment]
These variables determine the size of the nozzle that the program designs. There are two options, either:
1. You specify the thrust, and the program calculates the require size (exit radius) of the nozzle, or
2. You specify the exit radius of the nozzle, and the program calculates how much thrust it will produce.

I am glad the code is helpful for your research!

**Comment by murralog** [comment]
Thank you, 
I figured out my issue and now have a fully designed aerospike nozzle. It would not have been possible without your code.
![NICEPICOFSPIKE](https://user-images.githubusercontent.com/43050195/73049064-e809b200-3e40-11ea-9434-cea7cdb07b4c.JPG)
