### ISSUE TITLE
code differ from the source material

### ISSUE THREAD

**Issue by scantoread** [mvernacc/aerospike-nozzle-design-gui#3]
I'm referring to line 120 where you calculate the X_x axial coordinate.

find the X (axial) coordinate of the point. CC Lee Eqn (19)
            self.X[x] = (1 - self.RxRe[x]) / tan( nu_e - self.nu[x] + self.mu[x] )

CC Lee eqn 19 : X_x= (Re -Rx)/tan(phi)

I dont get why is it 1- RxRe instead of Re-Rx ?

**Comment by mvernacc** [comment]
`self.RxRe` and `self.X` are both dimensionless lengths, which are normalized by the outer radius R_e (see comments on [line 36](https://github.com/mvernacc/aerospike-nozzle-design-gui/blob/3e33c57c5015c300ab12d7f2a1d9d4ec633aefac/nozzle_solver.py#L36) and [line 38](https://github.com/mvernacc/aerospike-nozzle-design-gui/blob/3e33c57c5015c300ab12d7f2a1d9d4ec633aefac/nozzle_solver.py#L38)).

Starting from CC Lee's equation 19:
X_x= (R_e -R_x) / tan(phi)

divide both sides by R_e:
X_x / R_e = (1 - R_x / R_e) / tan(phi)

This is the equation which is evaluated on [line 120](https://github.com/mvernacc/aerospike-nozzle-design-gui/blob/3e33c57c5015c300ab12d7f2a1d9d4ec633aefac/nozzle_solver.py#L120), where `self.X[x]` is (X_x / R_e), `self.RxRe[x]` is (R_x / R_e), and `nu_e - self.nu[x] + self.mu[x]` is phi_x.

Maybe `self.X` should be re-named to make this clearer?

**Comment by scantoread** [comment]
sorry for not replying sooner.
i can't seem to find the source material "T. L. Deyound, "A Simplified Method for Plug Nozzle Design",
Technical Memorandum No. 140, July, 1960" so I kinda put this on the back burner.

Changing it or just putting a note on it would make it  clearer.

**Comment by mvernacc** [comment]
https://github.com/mvernacc/aerospike-nozzle-design-gui/commit/5a6f803b4d819ad99c4d710011763a7612438b67 changes variable names and adds comments to clarify this issue.
